name: melpa

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 25.1
          - 26.1
          - 27.1
        ignore_warnings:
          - true
        warnings_as_errors:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: true
            warnings_as_errors: true
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        check: melpa
        file: code-review.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
        warnings_as_errors: ${{ matrix.warnings_as_errors }}
